package com.axians.virtuallibrary.api.model.dto;

import javax.validation.constraints.NotBlank;

import com.axians.virtuallibrary.api.model.entity.Book;
import com.axians.virtuallibrary.commons.utils.Utils;
import com.axians.virtuallibrary.commons.utils.enums.CategoryBookEnum;
import com.axians.virtuallibrary.commons.utils.enums.StatusBookEnum;

import io.swagger.annotations.ApiModelProperty;

public class BookDTO {

	@NotBlank(message = "Title cannot be empty!")
	@ApiModelProperty(notes = "The title of the book", required = true, example = "Star Wars: Kennoby")
	private String title;

	@NotBlank(message = "Category cannot be empty!")
	@ApiModelProperty(notes = "The category of the book", required = true, example = "SCIENCE_FICTION")
	private String category;

	@ApiModelProperty(notes = "The quantity of this book in inventory(automatically generated by the system)", required = false, example = "5")
	private Integer inventory;
	
	@ApiModelProperty(notes = "The status of the book whether it is available or not(automatically generated by the system)", required = false, example = "true")
	private Boolean available;

	@ApiModelProperty(notes = "The unique identifier of any resource within the application(generated by the application Used UUID Generator version 4)", required = false, example = "52666e04-0872-492e-9134-8a4032ef05ab")
	private String resourceHyperIdentifier;
	
	@ApiModelProperty(notes = "The status of the book whether it is available, rented or disabled(automatically generated by the system)", required = false, example = "AVAILABLE")
	private StatusBookEnum status;
	
	public BookDTO() {}

	public BookDTO(String title, String category) {
		this.title = title;
		this.category = category;
	}
	
	public BookDTO(String title, String category, String resourceHyperIdentifier, StatusBookEnum status,
			Boolean available) {
		this.title = title;
		this.category = category;
		this.resourceHyperIdentifier = resourceHyperIdentifier;
		this.status = status;
		this.available = available;
	}
	
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Integer getInventory() {
		return inventory;
	}

	public void setInventory(Integer inventory) {
		this.inventory = inventory;
	}

	public String getResourceHyperIdentifier() {
		return resourceHyperIdentifier;
	}

	public void setResourceHyperIdentifier(String resourceHyperIdentifier) {
		this.resourceHyperIdentifier = resourceHyperIdentifier;
	}

	public StatusBookEnum getStatus() {
		return status;
	}

	public void setStatus(StatusBookEnum status) {
		this.status = status;
	}

	public Boolean getAvailable() {
		return available;
	}

	public void setAvailable(Boolean available) {
		this.available = available;
	}

	@Override
	public String toString() {
		return "BookDTO [title=" + title + ", category=" + category + ", inventory=" + inventory
				+ ", resourceHyperIdentifier=" + resourceHyperIdentifier + "]";
	}

	public Book generatePersistObject() {
		return new Book(title, CategoryBookEnum.getStatusBookEnum(category), resourceHyperIdentifier, status,
				available);
	}
	
	public Book generatePersistObjectToCreate() {
		 Book book = new Book(title, CategoryBookEnum.getStatusBookEnum(category));
		 book.setAvailable(true);
		 book.setResourceHyperIdentifier(Utils.generateResourceHyperIdentifier());
		 book.setStatus(StatusBookEnum.AVAILABLE);
		 return book;
	}

}
